# Generated by Django 3.0.2 on 2020-03-27 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gazette', '0004_auto_20200327_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
