# Generated by Django 3.0.2 on 2020-03-29 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gazette', '0006_auto_20200327_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='categorie',
            field=models.CharField(default='culture', max_length=200),
        ),
    ]
