# Generated by Django 3.0.2 on 2020-03-30 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gazette', '0008_auto_20200329_2035'),
    ]

    operations = [
        migrations.CreateModel(
            name='Numero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomNum', models.CharField(max_length=200)),
                ('num', models.FileField(blank=True, null=True, upload_to='static/fichier')),
                ('pub_dateNum', models.DateTimeField(verbose_name='date de publication')),
                ('illustration', models.ImageField(blank=True, null=True, upload_to='images/illustration')),
            ],
        ),
    ]
