# Generated by Django 3.0.2 on 2020-03-31 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gazette', '0009_numero'),
    ]

    operations = [
        migrations.RenameField(
            model_name='numero',
            old_name='pub_dateNum',
            new_name='pub_date',
        ),
        migrations.RenameField(
            model_name='numero',
            old_name='nomNum',
            new_name='titre',
        ),
    ]
