# Generated by Django 3.0.2 on 2020-04-07 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gazette', '0010_auto_20200331_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='formatPDF',
            field=models.FileField(blank=True, null=True, upload_to='articlePDF'),
        ),
    ]
