# Generated by Django 3.0.2 on 2020-04-07 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gazette', '0011_article_formatpdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='etat',
            field=models.CharField(default='non-publié', max_length=100),
        ),
        migrations.AddField(
            model_name='article',
            name='remarques',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='article',
            name='categorie',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='article',
            name='contenu',
            field=models.TextField(max_length=200000),
        ),
        migrations.AlterField(
            model_name='article',
            name='titre',
            field=models.CharField(default='Anonyme', max_length=200),
        ),
    ]
