# Generated by Django 3.0.2 on 2020-04-07 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gazette', '0012_auto_20200407_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='remarques',
            field=models.TextField(default='', max_length=200000),
        ),
    ]
