# Generated by Django 3.0.2 on 2020-04-07 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gazette', '0013_auto_20200407_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='remarques',
            field=models.TextField(blank=True, max_length=200000, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='titre',
            field=models.CharField(max_length=200),
        ),
    ]
