# Generated by Django 3.0.2 on 2020-04-09 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gazette', '0014_auto_20200407_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/image_publie'),
        ),
        migrations.AlterField(
            model_name='numero',
            name='num',
            field=models.FileField(blank=True, null=True, upload_to='static/media/fichier'),
        ),
    ]
