# Generated by Django 3.0.2 on 2020-04-09 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gazette', '0016_commentaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentaire',
            name='etat',
            field=models.CharField(default='non-publié', max_length=200),
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='auteur',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='commentaire',
            field=models.TextField(default=''),
        ),
    ]
