# Generated by Django 3.0.2 on 2020-04-09 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gazette', '0017_auto_20200409_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaire',
            name='commentaire',
            field=models.TextField(default='', max_length=20000),
        ),
    ]
