# Generated by Django 3.0.2 on 2020-04-11 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gazette', '0018_auto_20200409_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image_publie'),
        ),
        migrations.AlterField(
            model_name='numero',
            name='num',
            field=models.FileField(blank=True, null=True, upload_to='static/fichier'),
        ),
    ]
