# Generated by Django 3.0.2 on 2020-04-11 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gazette', '0019_auto_20200411_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='contenu',
            field=models.TextField(blank=True, max_length=200000, null=True),
        ),
        migrations.AlterField(
            model_name='numero',
            name='num',
            field=models.FileField(blank=True, null=True, upload_to='fichier'),
        ),
    ]
