# Generated by Django 3.0.2 on 2020-04-12 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gazette', '0020_auto_20200411_1630'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Commentaire',
        ),
    ]
