# Generated by Django 3.0.2 on 2020-04-13 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gazette', '0021_delete_commentaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auteur', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date de publication')),
                ('com', models.TextField(blank=True, null=True)),
                ('etat', models.CharField(max_length=200)),
            ],
        ),
    ]
