# Generated by Django 3.0.2 on 2020-04-13 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gazette', '0023_commentaire_article'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentaire',
            old_name='article',
            new_name='article_id',
        ),
    ]
