# Generated by Django 3.0.2 on 2020-04-13 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gazette', '0024_auto_20200413_1803'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Commentaire',
        ),
    ]
