# Generated by Django 3.0.2 on 2020-04-13 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gazette', '0027_auto_20200413_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaire',
            name='etat',
            field=models.CharField(default='non-publié', max_length=200),
        ),
    ]
