# Generated by Django 3.0.2 on 2020-04-14 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gazette', '0028_auto_20200413_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='mail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
